### ISSUE TITLE
Gradle build finished with 1 error(s)

### ISSUE THREAD

**Issue by jasongy** [sfsheng0322/In-depthStudy#5]
Error:Execution failed for task ':app:validateReleaseSigning'.

> Keystore file D:\studio_work\In-depthStudy\app\Users\sunfusheng\Android\keystore\app_keystore.jks not found for signing config 'release'.

**Comment by jasongy** [comment]
是要把那个app_keystore.jks 文件复制到D:\studio_work\In-depthStudy\app\Users\sunfusheng\Android\keystore，解决

**Comment by xiaokun19931126** [comment]
大哥，这个路径都没有啊
